// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/conduitio/conduit-connector-sdk/cmd/paramgen

package chaos

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (SourceConfig) Parameters() map[string]sdk.Parameter {
	return map[string]sdk.Parameter{
		"ackMode": {
			Default:     "success",
			Description: "ackMode controls what the Ack method should do.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"success", "error", "context-done", "block", "panic"}},
			},
		},
		"configureMode": {
			Default:     "success",
			Description: "configureMode controls what the Configure method should do.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"success", "error", "context-done", "block", "panic"}},
			},
		},
		"openMode": {
			Default:     "success",
			Description: "openMode controls what the Open method should do.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"success", "error", "context-done", "block", "panic"}},
			},
		},
		"readMode": {
			Default:     "success",
			Description: "readMode controls what the Read method should do.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"success", "error", "context-done", "block", "panic"}},
			},
		},
		"teardownMode": {
			Default:     "success",
			Description: "teardownMode controls what the Teardown method should do.",
			Type:        sdk.ParameterTypeString,
			Validations: []sdk.Validation{
				sdk.ValidationInclusion{List: []string{"success", "error", "context-done", "block", "panic"}},
			},
		},
	}
}
